SELECT
       P.PLAYER_NAME,
       T.TEAM_NAME,
       FT.FT_AVG_POINTS
    FROM LABSCHEMA.PLAYERS P
    JOIN LABSCHEMA.THROWS FT
      ON P.PLAYER_ID = FT.PLAYER_ID
    JOIN LABSCHEMA.TEAMS T
      ON P.TEAM_ID = T.TEAM_ID
;
