SELECT
       PLAYER_NAME,
       TEAM_NAME,
       VARCHAR_FORMAT(FT_AVG_POINTS, '999.9') AS FORMATTED_POINTS
    FROM LABSCHEMA.PLAYERS P
    JOIN LABSCHEMA.THROWS FT
      ON P.PLAYER_ID = FT.PLAYER_ID
    JOIN LABSCHEMA.TEAMS T
      ON P.TEAM_ID = T.TEAM_ID
      WHERE (P.TEAM_ID, FT.FT_AVG_POINTS) IN (
          SELECT P2.TEAM_ID, MAX(FT2.FT_AVG_POINTS)
              FROM LABSCHEMA.PLAYERS P2
              JOIN LABSCHEMA.THROWS FT2
                ON P2.PLAYER_ID = FT2.PLAYER_ID
              GROUP BY P2.TEAM_ID
          )
    ORDER BY FT.FT_AVG_POINTS DESC
;
