INSERT INTO LABSCHEMA.CONTACTS (
    LANG,
    SURNAME,
    FIRST_NAME,
    MIDDLE_NAME,
    ADDL_NAME,
    EMAIL_ADDR
) VALUES (
    'EN',
    'MAYERS',
    'CHERYL',
    'ANN',
    NULL,
    'CMAYERS@NOWHERE.COM'
);
INSERT INTO LABSCHEMA.CONTACTS (
    LANG,
    SURNAME,
    FIRST_NAME,
    MIDDLE_NAME,
    ADDL_NAME,
    EMAIL_ADDR
) VALUES (
    'ES',
    'RODRIGUEZ',
    'MIGUEL',
    'HORATIO',
    'SANCHEZ',
    'MRODRIGUEZ@THERE.NET'
);
