CREATE TABLE LABSCHEMA.PLAYERS (
    PLAYER_ID INT GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1, NO CACHE, NO CYCLE),
    PLAYER_NAME VARCHAR(100) NOT NULL,
    TEAM_ID INT NOT NULL
) IN DBMATE1.TSMATEDG;
