CREATE INDEX LABSCHEMA.IDX_TEAMS ON LABSCHEMA.TEAMS (TEAM_ID)
CLUSTER
DEFINE NO
PARTITION BY RANGE (
    PARTITION 1 ENDING AT (1000),
    PARTITION 2 ENDING AT (2000),
    PARTITION 3 ENDING AT (MAXVALUE)
);
