CREATE TABLE LABSCHEMA.TEAMS (
    TEAM_ID INT GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1, NO CACHE, NO CYCLE),
    TEAM_NAME VARCHAR(100) NOT NULL
) IN DBMATE1.TSMATEDG;
INSERT INTO LABSCHEMA.TEAMS (TEAM_NAME) VALUES ('MORTICIANS');
INSERT INTO LABSCHEMA.TEAMS (TEAM_NAME) VALUES ('NECROMANCERS');
INSERT INTO LABSCHEMA.TEAMS (TEAM_NAME) VALUES ('SAILORS');
INSERT INTO LABSCHEMA.TEAMS (TEAM_NAME) VALUES ('ZOOKEEPERS');
