INSERT INTO LABSCHEMA.THROWS (
    PLAYER_ID,
    FT_GAMES,
    FT_ATTEMPTS,
    FT_COMPLETED,
    FT_THREE_POINTERS,
    FT_PCT_COMPLETED,
    FT_AVG_POINTS,
    FT_LAST_UPDATE
) VALUES (
    (SELECT PLAYER_ID FROM LABSCHEMA.PLAYERS
        WHERE PLAYER_NAME = 'EDDIE THE EMBALMER'),
    86,
    267,
    105,
    6,
    39.3,
    2.5,
    '2024-07-01-14.56.11.000000'
);
----------------------------------------------------------------------
INSERT INTO LABSCHEMA.THROWS (
    PLAYER_ID,
    FT_GAMES,
    FT_ATTEMPTS,
    FT_COMPLETED,
    FT_THREE_POINTERS,
    FT_PCT_COMPLETED,
    FT_AVG_POINTS,
    FT_LAST_UPDATE
) VALUES (
    (SELECT PLAYER_ID FROM LABSCHEMA.PLAYERS
        WHERE PLAYER_NAME = 'CONNIE COFFINWRIGHT'),
    76,
    211,
    125,
    9,
    59.2,
    32.2,
    '2024-07-01-14.56.11.000000'
);
----------------------------------------------------------------------
INSERT INTO LABSCHEMA.THROWS (
    PLAYER_ID,
    FT_GAMES,
    FT_ATTEMPTS,
    FT_COMPLETED,
    FT_THREE_POINTERS,
    FT_PCT_COMPLETED,
    FT_AVG_POINTS,
    FT_LAST_UPDATE
) VALUES (
    (SELECT PLAYER_ID FROM LABSCHEMA.PLAYERS
        WHERE PLAYER_NAME = 'NANCY MANCER'),
    144,
    532,
    234,
    14,
    44.0,
    3.3,
    '2024-07-01-14.56.11.000000'
);
----------------------------------------------------------------------
INSERT INTO LABSCHEMA.THROWS (
    PLAYER_ID,
    FT_GAMES,
    FT_ATTEMPTS,
    FT_COMPLETED,
    FT_THREE_POINTERS,
    FT_PCT_COMPLETED,
    FT_AVG_POINTS,
    FT_LAST_UPDATE
) VALUES (
    (SELECT PLAYER_ID FROM LABSCHEMA.PLAYERS
        WHERE PLAYER_NAME = 'KELLY KEELHAULER'),
    106,
    622,
    408,
    16,
    65.6,
    3.7,
    '2024-07-01-14.56.11.000000'
);
----------------------------------------------------------------------
INSERT INTO LABSCHEMA.THROWS (
    PLAYER_ID,
    FT_GAMES,
    FT_ATTEMPTS,
    FT_COMPLETED,
    FT_THREE_POINTERS,
    FT_PCT_COMPLETED,
    FT_AVG_POINTS,
    FT_LAST_UPDATE
) VALUES (
    (SELECT PLAYER_ID FROM LABSCHEMA.PLAYERS
        WHERE PLAYER_NAME = 'RONNIE RUDDERMAN'),
    302,
    900,
    300,
    20,
    33.3,
    1.9,
    '2024-07-01-14.56.11.000000'
);
----------------------------------------------------------------------
INSERT INTO LABSCHEMA.THROWS (
    PLAYER_ID,
    FT_GAMES,
    FT_ATTEMPTS,
    FT_COMPLETED,
    FT_THREE_POINTERS,
    FT_PCT_COMPLETED,
    FT_AVG_POINTS,
    FT_LAST_UPDATE
) VALUES (
    (SELECT PLAYER_ID FROM LABSCHEMA.PLAYERS
        WHERE PLAYER_NAME = 'ANNIE AMPHIBIAN'),
    150,
    550,
    122,
    11,
    22.2,
    2.1,
    '2024-07-01-14.56.11.000000'
);
