CREATE TABLE LABSCHEMA.THROWS (
    THROW_ID INT GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1, NO CACHE, NO CYCLE),
    PLAYER_ID INT NOT NULL,
    FT_GAMES INT NOT NULL,
    FT_ATTEMPTS INT NOT NULL,
    FT_COMPLETED INT NOT NULL,
    FT_THREE_POINTERS INT NOT NULL,
    FT_PCT_COMPLETED DECIMAL(3,1) NOT NULL,
    FT_AVG_POINTS DECIMAL(4, 1) NOT NULL,
    FT_LAST_UPDATE TIMESTAMP WITH TIMEZONE
) IN DBMATE1.TSMATEDG;
